CREATE TABLE IF NOT EXISTS `#__payperdownloadplus_currencies` (
	`id` int(11) NOT NULL auto_increment,	
	`country` varchar(64),
	`currency` varchar(64),
	`iso` varchar(3),
   	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `#__payperdownloadplus_currencies` (`country`, `currency`, `iso`) VALUES
('Afghanistan', 'Afghan afghani', 'AFN'),
('Akrotiri and Dhekelia (UK)', 'European euro', 'EUR'),
('Aland Islands (Finland)', 'European euro', 'EUR'),
('Albania', 'Albanian lek', 'ALL'),
('Algeria', 'Algerian dinar', 'DZD'),
('American Samoa (USA)', 'United States dollar', 'USD'),
('Andorra', 'European euro', 'EUR'),
('Angola', 'Angolan kwanza', 'AOA'),
('Anguilla (UK)', 'East Caribbean dollar', 'XCD'),
('Antigua and Barbuda', 'East Caribbean dollar', 'XCD'),
('Argentina', 'Argentine peso', 'ARS'),
('Armenia', 'Armenian dram', 'AMD'),
('Aruba (Netherlands)', 'Aruban florin', 'AWG'),
('Ascension Island (UK)', 'Saint Helena pound', 'SHP'),
('Australia', 'Australian dollar', 'AUD'),
('Austria', 'European euro', 'EUR'),
('Azerbaijan', 'Azerbaijan manat', 'AZN'),
('Bahamas', 'Bahamian dollar', 'BSD'),
('Bahrain', 'Bahraini dinar', 'BHD'),
('Bangladesh', 'Bangladeshi taka', 'BDT'),
('Barbados', 'Barbadian dollar', 'BBD'),
('Belarus', 'Belarusian ruble', 'BYN'),
('Belgium', 'European euro', 'EUR'),
('Belize', 'Belize dollar', 'BZD'),
('Benin', 'West African CFA franc', 'XOF'),
('Bermuda (UK)', 'Bermudian dollar', 'BMD'),
('Bhutan', 'Bhutanese ngultrum', 'BTN'),
('Bolivia', 'Bolivian boliviano', 'BOB'),
('Bonaire (Netherlands)', 'United States dollar', 'USD'),
('Bosnia and Herzegovina', 'Bosnia and Herzegovina convertible mark', 'BAM'),
('Botswana', 'Botswana pula', 'BWP'),
('Brazil', 'Brazilian real', 'BRL'),
('British Indian Ocean Territory (UK)', 'United States dollar', 'USD'),
('British Virgin Islands (UK)', 'United States dollar', 'USD'),
('Brunei', 'Brunei dollar', 'BND'),
('Bulgaria', 'Bulgarian lev', 'BGN'),
('Burkina Faso', 'West African CFA franc', 'XOF'),
('Burundi', 'Burundi franc', 'BIF'),
('Cabo Verde', 'Cape Verdean escudo', 'CVE'),
('Cambodia', 'Cambodian riel', 'KHR'),
('Cameroon', 'Central African CFA franc', 'XAF'),
('Canada', 'Canadian dollar', 'CAD'),
('Caribbean Netherlands (Netherlands)', 'United States dollar', 'USD'),
('Cayman Islands (UK)', 'Cayman Islands dollar', 'KYD'),
('Central African Republic', 'Central African CFA franc', 'XAF'),
('Chad', 'Central African CFA franc', 'XAF'),
('Chatham Islands (New Zealand)', 'New Zealand dollar', 'NZD'),
('Chile', 'Chilean peso', 'CLP'),
('China', 'Chinese Yuan Renminbi', 'CNY'),
('Christmas Island (Australia)', 'Australian dollar', 'AUD'),
('Cocos (Keeling) Islands (Australia)', 'Australian dollar', 'AUD'),
('Colombia', 'Colombian peso', 'COP'),
('Comoros', 'Comorian franc', 'KMF'),
('Congo, Democratic Republic of the', 'Congolese franc', 'CDF'),
('Congo, Republic of the', 'Central African CFA franc', 'XAF'),
('Cook Islands (New Zealand)', 'Cook Islands dollar', '-'),
('Costa Rica', 'Costa Rican colon', 'CRC'),
('Cote d\'Ivoire', 'West African CFA franc', 'XOF'),
('Croatia', 'Croatian kuna', 'HRK'),
('Cuba', 'Cuban peso', 'CUP'),
('Curacao (Netherlands)', 'Netherlands Antillean guilder', 'ANG'),
('Cyprus', 'European euro', 'EUR'),
('Czechia', 'Czech koruna', 'CZK'),
('Denmark', 'Danish krone', 'DKK'),
('Djibouti', 'Djiboutian franc', 'DJF'),
('Dominica', 'East Caribbean dollar', 'XCD'),
('Dominican Republic', 'Dominican peso', 'DOP'),
('Ecuador', 'United States dollar', 'USD'),
('Egypt', 'Egyptian pound', 'EGP'),
('El Salvador', 'United States dollar', 'USD'),
('Equatorial Guinea', 'Central African CFA franc', 'XAF'),
('Eritrea', 'Eritrean nakfa', 'ERN'),
('Estonia', 'European euro', 'EUR'),
('Eswatini (formerly Swaziland)', 'Swazi lilangeni', 'SZL'),
('Ethiopia', 'Ethiopian birr', 'ETB'),
('Falkland Islands (UK)', 'Falkland Islands pound', 'FKP'),
('Faroe Islands (Denmark)', 'Faroese krona', '-'),
('Fiji', 'Fijian dollar', 'FJD'),
('Finland', 'European euro', 'EUR'),
('France', 'European euro', 'EUR'),
('French Guiana (France)', 'European euro', 'EUR'),
('French Polynesia (France)', 'CFP franc', 'XPF'),
('Gabon', 'Central African CFA franc', 'XAF'),
('Gambia', 'Gambian dalasi', 'GMD'),
('Georgia', 'Georgian lari', 'GEL'),
('Germany', 'European euro', 'EUR'),
('Ghana', 'Ghanaian cedi', 'GHS'),
('Gibraltar (UK)', 'Gibraltar pound', 'GIP'),
('Greece', 'European euro', 'EUR'),
('Greenland (Denmark)', 'Danish krone', 'DKK'),
('Grenada', 'East Caribbean dollar', 'XCD'),
('Guadeloupe (France)', 'European euro', 'EUR'),
('Guam (USA)', 'United States dollar', 'USD'),
('Guatemala', 'Guatemalan quetzal', 'GTQ'),
('Guernsey (UK)', 'Guernsey Pound', 'GGP'),
('Guinea', 'Guinean franc', 'GNF'),
('Guinea-Bissau', 'West African CFA franc', 'XOF'),
('Guyana', 'Guyanese dollar', 'GYD'),
('Haiti', 'Haitian gourde', 'HTG'),
('Honduras', 'Honduran lempira', 'HNL'),
('Hong Kong (China)', 'Hong Kong dollar', 'HKD'),
('Hungary', 'Hungarian forint', 'HUF'),
('Iceland', 'Icelandic krona', 'ISK'),
('India', 'Indian rupee', 'INR'),
('Indonesia', 'Indonesian rupiah', 'IDR'),
('International Monetary Fund (IMF)', 'SDR (Special Drawing Right)', 'XDR'),
('Iran', 'Iranian rial', 'IRR'),
('Iraq', 'Iraqi dinar', 'IQD'),
('Ireland', 'European euro', 'EUR'),
('Isle of Man (UK)', 'Manx pound', 'IMP'),
('Israel', 'Israeli new shekel', 'ILS'),
('Italy', 'European euro', 'EUR'),
('Jamaica', 'Jamaican dollar', 'JMD'),
('Japan', 'Japanese yen', 'JPY'),
('Jersey (UK)', 'Jersey pound', 'JEP'),
('Jordan', 'Jordanian dinar', 'JOD'),
('Kazakhstan', 'Kazakhstani tenge', 'KZT'),
('Kenya', 'Kenyan shilling', 'KES'),
('Kiribati', 'Australian dollar', 'AUD'),
('Kosovo', 'European euro', 'EUR'),
('Kuwait', 'Kuwaiti dinar', 'KWD'),
('Kyrgyzstan', 'Kyrgyzstani som', 'KGS'),
('Laos', 'Lao kip', 'LAK'),
('Latvia', 'European euro', 'EUR'),
('Lebanon', 'Lebanese pound', 'LBP'),
('Lesotho', 'Lesotho loti', 'LSL'),
('Liberia', 'Liberian dollar', 'LRD'),
('Libya', 'Libyan dinar', 'LYD'),
('Liechtenstein', 'Swiss franc', 'CHF'),
('Lithuania', 'European euro', 'EUR'),
('Luxembourg', 'European euro', 'EUR'),
('Macau (China)', 'Macanese pataca', 'MOP'),
('Madagascar', 'Malagasy ariary', 'MGA'),
('Malawi', 'Malawian kwacha', 'MWK'),
('Malaysia', 'Malaysian ringgit', 'MYR'),
('Maldives', 'Maldivian rufiyaa', 'MVR'),
('Mali', 'West African CFA franc', 'XOF'),
('Malta', 'European euro', 'EUR'),
('Marshall Islands', 'United States dollar', 'USD'),
('Martinique (France)', 'European euro', 'EUR'),
('Mauritania', 'Mauritanian ouguiya', 'MRU'),
('Mauritius', 'Mauritian rupee', 'MUR'),
('Mayotte (France)', 'European euro', 'EUR'),
('Mexico', 'Mexican peso', 'MXN'),
('Micronesia', 'United States dollar', 'USD'),
('Moldova', 'Moldovan leu', 'MDL'),
('Monaco', 'European euro', 'EUR'),
('Mongolia', 'Mongolian tugrik', 'MNT'),
('Montenegro', 'European euro', 'EUR'),
('Montserrat (UK)', 'East Caribbean dollar', 'XCD'),
('Morocco', 'Moroccan dirham', 'MAD'),
('Mozambique', 'Mozambican metical', 'MZN'),
('Myanmar (formerly Burma)', 'Myanmar kyat', 'MMK'),
('Namibia', 'Namibian dollar', 'NAD'),
('Nauru', 'Australian dollar', 'AUD'),
('Nepal', 'Nepalese rupee', 'NPR'),
('Netherlands', 'European euro', 'EUR'),
('New Caledonia (France)', 'CFP franc', 'XPF'),
('New Zealand', 'New Zealand dollar', 'NZD'),
('Nicaragua', 'Nicaraguan cordoba', 'NIO'),
('Niger', 'West African CFA franc', 'XOF'),
('Nigeria', 'Nigerian naira', 'NGN'),
('Niue (New Zealand)', 'New Zealand dollar', 'NZD'),
('Norfolk Island (Australia)', 'Australian dollar', 'AUD'),
('Northern Mariana Islands (USA)', 'United States dollar', 'USD'),
('North Korea', 'North Korean won', 'KPW'),
('North Macedonia (formerly Macedonia)', 'Macedonian denar', 'MKD'),
('Norway', 'Norwegian krone', 'NOK'),
('Oman', 'Omani rial', 'OMR'),
('Pakistan', 'Pakistani rupee', 'PKR'),
('Palau', 'United States dollar', 'USD'),
('Palestine', 'Israeli new shekel', 'ILS'),
('Panama', 'United States dollar', 'USD'),
('Papua New Guinea', 'Papua New Guinean kina', 'PGK'),
('Paraguay', 'Paraguayan guarani', 'PYG'),
('Peru', 'Peruvian sol', 'PEN'),
('Philippines', 'Philippine peso', 'PHP'),
('Pitcairn Islands (UK)', 'New Zealand dollar', 'NZD'),
('Poland', 'Polish zloty', 'PLN'),
('Portugal', 'European euro', 'EUR'),
('Puerto Rico (USA)', 'United States dollar', 'USD'),
('Qatar', 'Qatari riyal', 'QAR'),
('Reunion (France)', 'European euro', 'EUR'),
('Romania', 'Romanian leu', 'RON'),
('Russia', 'Russian ruble', 'RUB'),
('Rwanda', 'Rwandan franc', 'RWF'),
('Saba (Netherlands)', 'United States dollar', 'USD'),
('Saint Barthelemy (France)', 'European euro', 'EUR'),
('Saint Helena (UK)', 'Saint Helena pound', 'SHP'),
('Saint Kitts and Nevis', 'East Caribbean dollar', 'XCD'),
('Saint Lucia', 'East Caribbean dollar', 'XCD'),
('Saint Martin (France)', 'European euro', 'EUR'),
('Saint Pierre and Miquelon (France)', 'European euro', 'EUR'),
('Saint Vincent and the Grenadines', 'East Caribbean dollar', 'XCD'),
('Samoa', 'Samoan tala', 'WST'),
('San Marino', 'European euro', 'EUR'),
('Sao Tome and Principe', 'Sao Tome and Principe dobra', 'STN'),
('Saudi Arabia', 'Saudi Arabian riyal', 'SAR'),
('Senegal', 'West African CFA franc', 'XOF'),
('Serbia', 'Serbian dinar', 'RSD'),
('Seychelles', 'Seychellois rupee', 'SCR'),
('Sierra Leone', 'Sierra Leonean leone', 'SLL'),
('Singapore', 'Singapore dollar', 'SGD'),
('Sint Eustatius (Netherlands)', 'United States dollar', 'USD'),
('Sint Maarten (Netherlands)', 'Netherlands Antillean guilder', 'ANG'),
('Slovakia', 'European euro', 'EUR'),
('Slovenia', 'European euro', 'EUR'),
('Solomon Islands', 'Solomon Islands dollar', 'SBD'),
('Somalia', 'Somali shilling', 'SOS'),
('South Africa', 'South African rand', 'ZAR'),
('South Georgia Island (UK)', 'Pound sterling', 'GBP'),
('South Korea', 'South Korean won', 'KRW'),
('South Sudan', 'South Sudanese pound', 'SSP'),
('Spain', 'European euro', 'EUR'),
('Sri Lanka', 'Sri Lankan rupee', 'LKR'),
('Sudan', 'Sudanese pound', 'SDG'),
('Suriname', 'Surinamese dollar', 'SRD'),
('Svalbard and Jan Mayen (Norway)', 'Norwegian krone', 'NOK'),
('Sweden', 'Swedish krona', 'SEK'),
('Switzerland', 'Swiss franc', 'CHF'),
('Syria', 'Syrian pound', 'SYP'),
('Taiwan', 'New Taiwan dollar', 'TWD'),
('Tajikistan', 'Tajikistani somoni', 'TJS'),
('Tanzania', 'Tanzanian shilling', 'TZS'),
('Thailand', 'Thai baht', 'THB'),
('Timor-Leste', 'United States dollar', 'USD'),
('Togo', 'West African CFA franc', 'XOF'),
('Tokelau (New Zealand)', 'New Zealand dollar', 'NZD'),
('Tonga', 'Tongan pa\'anga', 'TOP'),
('Trinidad and Tobago', 'Trinidad and Tobago dollar', 'TTD'),
('Tristan da Cunha (UK)', 'Pound sterling', 'GBP'),
('Tunisia', 'Tunisian dinar', 'TND'),
('Turkey', 'Turkish lira', 'TRY'),
('Turkmenistan', 'Turkmen manat', 'TMT'),
('Turks and Caicos Islands (UK)', 'United States dollar', 'USD'),
('Tuvalu', 'Australian dollar', 'AUD'),
('Uganda', 'Ugandan shilling', 'UGX'),
('Ukraine', 'Ukrainian hryvnia', 'UAH'),
('United Arab Emirates', 'UAE dirham', 'AED'),
('United Kingdom', 'Pound sterling', 'GBP'),
('United States of America', 'United States dollar', 'USD'),
('Uruguay', 'Uruguayan peso', 'UYU'),
('US Virgin Islands (USA)', 'United States dollar', 'USD'),
('Uzbekistan', 'Uzbekistani som', 'UZS'),
('Vanuatu', 'Vanuatu vatu', 'VUV'),
('Vatican City (Holy See)', 'European euro', 'EUR'),
('Venezuela', 'Venezuelan bolivar', 'VES'),
('Vietnam', 'Vietnamese dong', 'VND'),
('Wake Island (USA)', 'United States dollar', 'USD'),
('Wallis and Futuna (France)', 'CFP franc', 'XPF'),
('Yemen', 'Yemeni rial', 'YER'),
('Zambia', 'Zambian kwacha', 'ZMW'),
('Zimbabwe', 'United States dollar', 'USD');